 name: Issue Vulnerable

 on:
   issues:
     types: [opened]
 jobs:
   commentCreated:
     runs-on: ubuntu-latest
     env: 
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - run: echo "$ISSUE_TITLE"
       #- run: echo "${{ github.event.issue.title }}"
